steps:
#  - name: 'gcr.io/cloud-builders/terraform'
#    args: ['apply --auto-approve']
#    dir: 'src/frontend'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'src/frontend'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'src/frontend'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-d', 'src/frontend/build', 'gs://writeshite-frontend']

  - name: gradle:8-jdk8
    entrypoint: gradle
    args: ['jib', '--stacktrace']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/writeshite-backend:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'writeshite-backend', '--image', 'gcr.io/$PROJECT_ID/writeshite-backend', '--region', 'us-central1', '--platform', 'managed']

serviceAccount: 'projects/peaceful-app-379819/serviceAccounts/build-bot@peaceful-app-379819.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY