steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Commit SHA: $COMMIT_SHA"

  # Deploy infrastructure using Terraform
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['init']
    dir: 'terraform'
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']
    dir: 'terraform'
    env:
      - 'TF_VAR_project_id=$PROJECT_ID'
      - 'TF_VAR_commit_sha=$COMMIT_SHA'

  # Build the backend
  - name: 'gcr.io/distroless/java21-debian12:debug'
    entrypoint: '/busybox/sh'
    args:
      - -c
      - |
        ln -s /busybox/sh /bin/sh
        ln -s /busybox/env /usr/bin/env
        /workspace/gradlew --console=plain --no-daemon --gradle-user-home=/home/.gradle :jib -Djib.to.image=gcr.io/$PROJECT_ID/writeshite-backend:latest

  # Build the frontend
  - name: 'node:lts'
    entrypoint: 'npm'
    args: ['install']
    dir: 'src/frontend'
  - name: 'node:lts'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'src/frontend'

# Push the frontend files to GCS
artifacts:
  objects:
    location: 'gs://writeshite-frontend/'
    paths: ['src/frontend/build/**']

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 'projects/peaceful-app-379819/serviceAccounts/build-bot@peaceful-app-379819.iam.gserviceaccount.com'