steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'src/frontend'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'src/frontend'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-d', 'src/frontend/build', 'gs://writeshite-frontend']

  - name: gradle:8.7-jdk21
    entrypoint: gradle
    args: ['jib', '--image=gcr.io/$PROJECT_ID/writeshite-backend:latest', '--stacktrace']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/writeshite-backend:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/writeshite-backend:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        if gcloud compute instances describe writeshite-instance --zone us-central1-a; then
          gcloud compute instances stop writeshite-instance --zone us-central1-a
        else
          echo "Instance writeshite-instance does not exist, skipping stop."
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['compute', 'instances', 'set-machine-type', 'writeshite-instance', '--machine-type=e2-micro', '--zone', 'us-central1-a']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        if gcloud compute instances describe writeshite-instance --zone us-central1-a; then
          gcloud compute instances start writeshite-instance --zone us-central1-a
        else
          echo "Instance writeshite-instance does not exist, skipping start."
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['compute', 'ssh', 'writeshite-instance', '--zone', 'us-central1-a', '--command', 'sudo docker pull gcr.io/$PROJECT_ID/writeshite-backend:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['compute', 'ssh', 'writeshite-instance', '--zone', 'us-central1-a', '--command', 'sudo docker stop writeshite-backend || true && sudo docker rm writeshite-backend || true']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['compute', 'ssh', 'writeshite-instance', '--zone', 'us-central1-a', '--command', 'sudo docker run -d --name writeshite-backend -p 8080:8080 gcr.io/$PROJECT_ID/writeshite-backend:latest']

serviceAccount: 'projects/peaceful-app-379819/serviceAccounts/build-bot@peaceful-app-379819.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY
