steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret="terraform-sa-key" > terraform-sa-key.json
        export GOOGLE_APPLICATION_CREDENTIALS="$PWD/terraform-sa-key.json"
  - name: 'hashicorp/terraform'
    args: ['init']
  - name: 'hashicorp/terraform'
    args: ['apply', '-auto-approve']

  # Frontend build steps
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'
  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'frontend/build/*', 'gs://writeshite-frontend/']

  # Backend build steps
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']
    dir: 'backend'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/your-project-id/backend', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/your-project-id/writeshite-backend:latest']