version: '3'

services:
  proxy:
    image: staticfloat/nginx-certbot
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: "writeshitewebsite@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
    networks:
      - writeshite-net

  writeshite-backend:
    image: julesjulesandjulian/writeshite-backend:latest
    restart: unless-stopped
    networks:
      - writeshite-net

  writeshite-frontend:
    image: julesjulesandjulian/writeshite-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - writeshite-net

networks:
  writeshite-net:
    driver: bridge
