name: CI/CD Pipeline
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/writeshite-backend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/writeshite-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into Unraid server and build frontend
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.UNRAID_HOST }}
          username: ${{ secrets.UNRAID_USER }}
          password: ${{ secrets.UNRAID_PASSWORD }}
          script: |
            cd /mnt/user/appdata/writeshite/frontend
            npm install
            npm run build

      - name: SSH into Unraid server and pull the latest Docker image
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.UNRAID_HOST }}
          username: ${{ secrets.UNRAID_USER }}
          password: ${{ secrets.UNRAID_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/writeshite-backend:latest
            docker-compose -f /mnt/user/appdata/writeshite/docker-compose.yml up -d
